# Revisions to images that were generated before the module generations system was implemented and which are not (yet) generated by other python code.

import helper

#helper.save_image({
#    "filename":"World Energy Scenarios.jpg",
#    "status":"Done",
#    "details":"John requests the following changes. Give the sources as BP and UN. Move the logo to the upper right corner. For the Constant Energy and Constant Energy per Capita scenarios, clarify that they are based on 2017 consumption rates.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"World Primary Energy.jpg",
#    "status":"Done",
#    "details":"Add vertical bars over the dates so it is easier to see the exact year for each point on the plot. In general, time series plots should have this feature for ease of reading.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Rebound Effect 2.jpg",
#    "status":"Done",
#    "details":"Change all occurrences of 'Electricity' to 'Electricity Production'.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"img2019_06_11_elec_ghg.jpg",
#    "status":"Done",
#    "details":"This is the GHG from electricity plot. All labels should be on a single line.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"coal_externality.jpg",
#    "status":"Done",
#    "details":"A figure to be added here: 1.099 &cent;/kWh for Transportation externalities. I would also like to have a good figure to be added related to disposal, but I haven't found it yet. The reference here is just for the transportation figure and not the other ones.",
#    "references":["coal_external"],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Cost of Gas Power.jpg",
#    "status":"Done",
#    "details":"Try putting the &cent;/kWh symbol on the axis rather than in the body of the plot (e.g. 25 &cent;/kWh at the top). Generally speaking, it is good to get rid of stray bits of text as much as possible. If you try it and it just doesn't work graphically, let me know.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"img2019_06_11_rp.jpg",
#    "status":"Done",
#    "details":"Clarify on the plot that 'reserves' are known reserves of the material that can be produced economically at today's market conditions. Generally speaking, we want to be sure that on all plot, it is reasonably clear what the terms mean. While we're at it, add that the data source is the World Energy Council. We eventually want to have source information on most plots, except where there is a reason that doesn't apply. There is also a typo to fix: reserves of natural gas are in cubic meters, not cubit meters.<br><br><b>Added November 19, 2019:</b> I forgot to include this earlier, but it is important that units are always clear in doing bar plots. In this case, the units are Years. That is, the number of years that current reserves will last at current production rates.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Cost of Solar Power 2.jpg",
#    "status":"Done",
#    "details":"In the title, add 'Non-PV' somewhere to distinguish it from the PV plot.<br><br>At some point, I want to have a Distributed Electricity LCOE plot, which will include the three distributed solar options, as well as micro hydro, micro wind, and others. More work on my part is needed before the data is ready for that. For now, I think the best thing would be to make two versions of this: one with and one without the three distributed options.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"industrial_heat2.jpg",
#    "status":"Done",
#    "details":"Something's wrong with the Biomass bar here. It looks like it is shifted to the right of where it should be, due to the negative lower bound.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"World Primary Energy Consumption in Buildings.jpg",
#    "status":"Done",
#    "details":"The title should have a ' - World' in it, to distinguish it from the US version. Compress the 'Note'; it most certainly should not go to a second line. You could make the last bar 'Appliances*' and the Note line is replaced by '* includes Refrigeration'. BTW we need that because for the US version, Refrigeration is a separate category. Or, if there was a way to change the label to 'Appliances (including Refrigeration)' so that it all fits on a single line, that would be even better.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Density and Energy.jpg",
#    "status":"Done",
#    "details":"Lots to do here. Rearrange the five categories so that the ones that change the least are on the left. Then put the labels under the bars for the one at the bottom. Stagger them if necessary. The labels can all be shortened. There is no need to say 'Energy' in all of them; 'Energy in Commercial Buildings' could just be 'Commercial Buildings'. The logo might be more comfortable in the upper right.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"National Density Scenarios.jpg",
#    "status":"Done",
#    "details":"Same principles as in Density and Energy.jpg apply here, so I am copying that text over. Lots to do here. Rearrange the five categories so that the ones that change the least are on the left. Then put the labels under the bars for the one at the bottom. Stagger them if necessary. The labels can all be shortened. There is no need to say 'Energy' in all of them; 'Energy in Commercial Buildings' could just be 'Commercial Buildings'. The logo might be more comfortable in the upper right.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"dhc_viability.jpg",
#    "status":"Done",
#    "details":"For scenarios where district heating/cooling is not viable, add a bit of text saying 'Not Viable' or something like that. Nonviability is implicit in the lack of a bar, but it might be clearer if made explicit.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Zoning Costs.jpg",
#    "status":"Done",
#    "details":"Get rid of the GHG portion of it, as it is too similar to the energy portion. For the remaining two, try rearranging it so there are four labels on a single plot, each of which has two bars (one for energy and one for land use). Right now it is a little unclear because they compare the same four things but in different orders. We'll see if this revised version looks better.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Annual Parking Cost.jpg",
#    "status":"Done",
#    "details":"Move the logo to the upper right. For the key, there is no need to keep the word 'Costs' in each label. Then scooch the keys to the right so they better line up with the bars. The zero value in the bottom one makes it a bit more complicated to line up keys with bars, but we can get creative and make it work.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"img2019_05_23_fuelecon.jpg",
#    "status":"Done",
#    "details":"Make the 'Overall' bar a different shade from the others.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"LCOE.jpg",
#    "status":"Done",
#    "details":"It would be nice if we could get some more definition here, particularly on the low (0 to 10 cent range) end of the plot where the most interesting action is. One option would be to turn the bars horizontal. Another would be to move the logo to the right, under the key so that the plot could be extended vertically.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"storage_efficiency.jpg",
#    "status":"Done",
#    "details":"Adding a new option, Ammonia, to the list. It's efficiency is 72%. That figure comes from Wang et al.; the ones that are already there are from Schmidt et al.",
#    "references":["schmidt","ammonia_storage"],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Heating Source Consumption and Emissions.jpg",
#    "status":"Done",
#    "details":"John requested a revision here to use more recent carbon intensity figures for US electricity. The revised version will be based on 2018 numbers rather than 2014 numbers; otherwise, it is unchanged. Change the CO2 figures to the following: Geothermal Heat Pump should be 3.1; Air-Source Heat Pump (high performance) should be 4.0; Air-Source Heat Pump (low performance) should be 8.4; Hydrogen from Electrolysis should be 8.9; Electric Resistance (note spelling on 'Resistance') Heater should be 12.8. The non-electric modes are unchanged. (Note to MG: details are in 'heating and cooling' notes; conversion to python script may be needed later.)",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"nuclear_plant_cost.jpg",
#    "status":"Done",
#    "details":"What was there before is as follows. I only just now noticed that in the current version, costs are reported as dollars per kWh. It should be cents per kWh, so what is on the site now is too high by a factor of 100.<br><br>Show capital and operating costs for a new nuclear plant in the US. As these figures are dominated by capital costs, be aware that the results are highly dependent on calculation assumptions. Figures are cents per kWh. Most data comes from the World Nuclear Association.<br><br>Capital: 8.05<br>Operations and Maintenance (excluding fuel): 1.64<br>Fuel: 0.76<br>Waste Disposal: 0.1<br>Decomissioning: 0.15",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"nuclear_waste_options.jpg",
#    "status":"Done",
#    "details":"The figures need to be presented as cents per kWh, not dollars per kWh. What is on the site is 100X too high.<br><br>Show estimated costs for various long-term nuclear waste management options. There are four sources, which are listed in the text of the Nuclear section. Note that these costs are quite small relative to other costs around power generation. They are all in cents per kWh.<br>Near-Surface Repository: 0.003-0.021<br>Cavern/Geological Repository: 0.012-0.039<br>Deep Borehole: 0.04<br>Sub-Seabed Disposal: 0.018-0.04<br>Partitioning and Transmutation: 0.134<br>Reprocessing: 0.20-0.26",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"nuclear_external.jpg",
#    "status":"Done",
#    "details":"I think we will get rid of the Mining, Enrichment, Disposal bar and add bars for each of these separately, all from the listed source. For mining and milling, the value is 0.024 cents/kWh. For enrichment, the value is 0.0026 cents/kWh. For disposal, it's 1.1*10<sup>-5</sup> cents/kWh. These values are significantly less than the value they are replacing, and I'm not sure what the reason for this is other than deriving from a different source.",
#    "references":["nuke_external"],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"uranium_mining.jpg",
#    "status":"Done",
#    "details":"Figures need to be presents as cents per kWh, not dollars per kWh. What is on the site now is 100X too high.<br><br>Show the cost, both per kilogram uranium oxide (U3O8). The key piece, the estimated cost of uranium recovery from seawater, comes from this paper. Figures on uranium spot prices come from news articles, and conversion of per-kg (8.9 kg U3O8 to make one kg of fuel, and one kg of fuel produces 360,000 kWh) prices to per-kWh prices come from figures here. The figures for thorium come from p. 87 of this paper, and are based on what the price of uranium would have to be for the thorium reprocessing cycle to be economically competitive. Present this as two side-by-side plots, one with the per-kg figures and the other with the per-kWh figures.<br><br>U3O8 spot price, 2018-19: $60/kg and 0.15 cents/kWh<br>U3O8 spot price, 1980 and 2007 peaks: $300/kg and 0.75 cents/kWh<br>Thorium: $400/kg (U-fuel equivalent), 1.0 cents/kWh<br>Seawater Recovery: $500/kg and 1.24 cents/kWh.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"img2019_06_11_potential.jpg",
#    "status":"Done",
#    "details":"This is the Power Production Potential plot again. Add vertical lines indicating 0 and 600 EJ, the latter of which is approximately current world primary energy. See also, the new caption on the Energy Production page with details source information.<br><br>Another change, as of June 2, 2020. Add a bar for biomethane, for which the potential is 30.8 EJ/year.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"biomass_external.jpg",
#    "status":"Done",
#    "details":"Costs should be in cents/kWh, not dollars per kWh.",
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"hydro_external.jpg",
#    "status":"Done",
#    "details":"The Internal Costs value is fine, but the GHG exteranlities should be 0.35 cents/kWh, not 35 cents/kWh. Similiarly, the value for non-GHG externalities should be 0.51 cents/kWh.",
#    "source_file":"image_revisions.py"
#})

#aea_table = [
#    ["<b>Purpose</b>","<b>Electricity needed, as share of ammonia output energy</b>"],
#    ["Air splitting", 0.008],
#    ["Water splitting", 1.43],
#    ["Synthesis", 0.071],
#    ["Distribution", 0.008]
#]
#helper.save_image({
#    "filename":"ammonia_electrolysis_energy.jpg",
#    "status":"Done",
#    "table":aea_table,
#    "details":"This is roughly what we had before. But the units were wrong. I said GJ/ton before, but really it should be GJ per GJ heating value of ammonia. If you look carefully you will see the numbers, as reported, differ drastically from ammonia energy in the other plot, which is what tipped me off.",
#    "references":["dana"],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"fusion_reactions.jpg",
#    "status":"Done",
#    "details":"Put together an infographic showing the characteristics of three main fusion reactions. Data is here (fusion_reactions.csv). The units for power density are (W/m3/kPa2), for temperature are millions of kelvin, and the neutronicity figure is the fraction of energy released in the form of neutrons (dimensionless number). In the reaction formulas, whenever a number directly precedes (i.e. no space) a chemical element, that number is the atomic mass and it should be presented in superscript. Check the Wikipedia page (Nuclear fusion), about half way down, if you aren't sure, though note that I left off the atomic number in the equations. Source data is on the Nuclear Fusion page. There are four sources that come into play here. For the advantages and disadvantages, those are observations that come with a general familiarity with nuclear fusion and don't need to be sourced.",
#    "references":[],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"wave_deployment.jpg",
#    "status":"Done",
#    "details":"The LCOE of energy on the plot on the right should range from about 6-16 &cent;/kWh, not 0.06-0.16 &cent;/kWh.",
#    "references":[],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Cost of Geothermal Power.jpg",
#    "status":"Done",
#    "details":"There are two LCOE estimates for Hydrothermal Sea Vents to add to the chart. Hydrothermal Sea Vents are not to be confused with Hydrothermal or Hydrothermal Vents, which have similar names.",
#    "references":[],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"mhk_cost.jpg",
#    "status":"Done",
#    "details":"Replace OTEC with the full phrase, Ocean Thermal Exchange Current. Marine Current and River Current should be singular.",
#    "references":[],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"Cost of Solar Power.jpg",
#    "status":"Done",
#    "details":"There is an estimate of 3.72 &cent;/kWh to be added for LSC. This is a new category. There is also a 3.5-4.9 &cent;/kWh to be added for perovskites, which is an existing category.",
#    "references":[],
#    "source_file":"image_revisions.py"
#})

#helper.save_image({
#    "filename":"img2019_06_11_elec_land.jpg",
#    "status":"Done",
#    "details":"A couple changes needed here. I don't think the Geothermal number is right (it is in the paper itself, not something we did), so I got it from another source. The new Geothermal number is 45.0264 m^2/kW. While we're at it, we have 168.63 m^2/kW for solar thermal (the existing Solar bar should be relabled Solar PV for clarity). Both of those come from Trainor et al. Also put in a figure of 41.68 m^2/kW for tranmission, which comes from Stevens et al. The rest are from van Zalk and Behrens as before, but one thing to fix on the graphic: it is van Zalk and Behrens, not Zalk and Behrens. It's not easy to get reliable figures on this subject.",
#    "references":["vanzalk","trainor","strata_landuse"],
#    "source_file":"image_revisions.py"
#})