# Calculations related to light pollution

# -*- coding: utf-8 -*-

import helper

lp_table = [
    ["<b>Metric</b>","<b>Percentage</b>"],
    ["People under light pollution, world","83%"],
    ["People under light pollution, US and Europe","99%"],
    ["People who can't see Milky Way, world","34%"],
    ["People who can't see Milky Way, North America","80%"],
    ["People who can't see Milky Way, Europe","60%"],
    ["Land under light pollution","23%"]
]

helper.save_image({
    "filename":"lp_extent.jpg",
    "status":"Done",
    "details":"Some figures on the extent of light pollution. According to Hu and Zhang, global TNL (total nighttime lights) was 2.1*10<sup>8</sup> in 1992 and 4.7*10<sup>8</sup> in 2017. TNL is a measure of the total amount of artificial light. We don't need to worry about what exactly that means here; it's the increase that is most relevant. Data in the included table comes from Falchi et al. They define light pollution to be a situation where artificial light contributes at least 8% of the natural background light at the point of maximum darkness, typically around 1 AM. The Milky Way becomes invisible when artificial light is about 400% (4X) natural light.",
    "table":lp_table,
    "references":["tnl","lp_stats"],
    "source_file":"light_pollution.py"
})

############################################## Personal exposure to light pollution

lp_exposure = [
    ["<b>Exposure factor</b>","<b>Intensity (lux)</b>"],
    ["Overcast night sky","0.00003-0.0001"],
    ["Clear starry night","0.001"],
    ["Full moon","0.1-0.3"],
    ["Typical urban skyglow","0.15"],
    ["Lit residential side street","5"],
    ["Lighted parking lot","10"],
    ["Main road street lighting","15"],
    ["Tablet computer (9.7 inch)","40"],
    ["Smartphone","40+"],
    ["ICU step-down unit","1.3-47.3"],
    ["Computer screen (LED, 24 inch)","100"],
    ["ICU","190.5"],
    ["Typical home","100-300"]
]

# light_exposure

helper.save_image({
    "filename":"lp_exposure.jpg",
    "status":"Done",
    "details":"A few figures on a person's typical exposure to light at night. Smartphone exposure is estimated at 40+ blux, which is a weighted measure of light intensity based on circadian-response frequencies. I would treat it as lux, like the others, for the purposes of graphical portrayal.",
    "table":lp_exposure,
    "references":["light_exposure"],
    "source_file":"light_pollution.py"
})

############################################## Street lights

helper.save_image({
    "filename":"streetlight.jpg",
    "status":"Done",
    "details":"A simple plot showing that of light generated by street lights, 40% is used productively, 10% goes to glare, and 50% is wasted light (goes up and contributes to skyglow but does not illuminate what is needed).",
    "references":["lp_streetlight"],
    "source_file":"light_pollution.py"
})

############################################## Type of light and pollution generated

lighttype_table = [
    ["<b>Type</b>","<b>Melatonin Suppression Index</b>","<b>Induced Photosynthesis Index</b>","<b>Star Light Index</b>"],
    ["Low Pressure Sodium",0.008,0.349,0.078],
    ["High Pressure Sodium",0.099,0.465,0.188],
    ["Metal Halide",0.634,0.651,0.567],
    ["Halogen",0.364,0.761,0.583],
    ["Incandescent",0.241,0.820,0.474],
    ["Fluorescent T8 cool-white",0.427,0.594,0.595],
    ["LED 5000 K",0.533,0.631,0.610],
    ["Philips LED 4000K",0.445,0.607,0.550],
    ["LED 2700 K",0.280,0.516,0.349],
    ["Nichia Amber",0.037,0.598,0.156],
    ["Lumiled PC Amber",0.042,0.540,0.140],
    ["LED 5000 K Filtered",0.162,0.437,0.362],
    ["LED 2700 K Filtered",0.071,0.403,0.214],
    ["Sun",1,1,1]
]

helper.save_image({
    "filename":"light_type.jpg",
    "status":"Done",
    "table":lighttype_table,
    "details":"This table shows three metrics about types of lights: the Melatonin Suppression Index, the Induced Photosynthesis Index, and the Star Light Index. Each of these could be regarded as a facet of light pollution, so the lower the better (for nighttime lights, so this principle doesn't apply to the Sun). The numbers represent the ratio of the three indices to the amount of useful light that is generated, all normalized so the Sun is 1. This means, for instance, that Low Pressure Sodium lights block out stars 7.8% as much as the Sun relative to the amount of light it generates, while HPS lights blocks out 18.8% as much, so HPS is worse from a light pollution standpoint. The last two LEDs that are filtered refer to Ledtech's <i>Equilib</i> filter. The temperatures of the LEDs are in Kelvin. Higher temperatures mean higher wavelenghts of light generated. The 5000 K light generates more blue wavelengths than the 2700 K light, so more light pollution because the atmosphere is more effective at scattering high wavelengths.",
    "references":["lp_lighttype"],
    "source_file":"light_pollution.py"
})