import helper

helper.save_image({
    "filename":"nwaste_compo.jpg",
    "status":"Done",
    "details":"Basic plot on the three top level components of nuclear waste and their prevalence by mass and radioactivity.",
    "table":[
        ["<b>Component</b>","<b>Share of waste by volume</b>","<b>Share of waste by radioactivity</b>","<b>Explanation</b>"],
        ["High Level Waste","3%","95%","Used fuel, fission products, transuranic elements created by neutron bombardment. Requires shielding and cooling."],
        ["Intermediate Level Waste","7%","4%","Contaminated reactor components. Requires shielding but not cooling."],
        ["Low Level Waste","90%","1%","Lightly contaminated items"]
    ],
    "references":["wn_waste"],
    "source_file":"nuclear_waste.py"
})

helper.save_image({
    "filename":"lhw_lifetime.jpg",
    "status":"Not Done",
    "details":"How long is high level waste dangerous? This chart gets at some of that. I would also be interested in adding some figures on how these figures compare to dangerous or fatal exposures to humans, but I don't have those yet. The plot in the original source is a time series with a log-log plot.",
    "table":[
        ["<b>Years After Fission</b>","<b>Radioactivity relative to uranium ore containing the same amount of uranium</b>"],
        [30,10000],
        [140,1000],
        [2000,100],
        [43000,10]
    ],
    "references":["hlw_lifetime"],
    "source_file":"nuclear_waste.py"
})

hlw_table = [
    ["<b>Product</b>","<b>Mass in kilograms produced from fissioning 1 ton of uranium</b>","<b>Half-life</b>","<b>Notes</b>"],
    ["Uranium-238",940.6,"4.468 billion years"],
    ["Uranium-235",10.3,"704 million years"],
    ["Uranium-236",4.4,"23.42 million years"],
    ["Uranium-234",0.2,"245.5 thousand years"],
    ["Plutonium-238",0.18,"87.74 years","Useful for radioisotope thermal generators"],
    ["Plutonium-239",5.67,"24.1 thousand years","The most concerning long-term isotope"],
    ["Plutonium-240",2.21,"6560 years"],
    ["Plutonium-241",1.19,"14.4 years"],
    ["Plutonium-242",0.49,"376 thousand years"],
    ["Neptunium-237",0.43,"2.144 million years"],
    ["Americium-241",0.22,"432.2 years"],
    ["Americium-242",0.0007,"141 years"],
    ["Americium-243",0.1,"7370 years"],
    ["Curium-242",0.00013,"160 days"],
    ["Curium-243",0.00032,"29.1 years"],
    ["Curium-244",0.024,"18.1 years"],
    ["Short and intermediate-lived fission products",31.1,"The greatest concerns are strontium-90 and caesium-137, with half lives of 28.9 and 30.17 years respectively. The rest of the FP's have half lives 10 years or less."],
    ["Technetium-99",0.81,"211.1 thousand years"],
    ["Iodine-129",0.17,"15.7 million years"],
    ["Caesium-135",1.31,"2.3 million years"],
    ["Zirconium-93",0.71,"1.53 million years"]
]

helper.save_image({
    "filename":"hlw_composition.jpg",
    "table":hlw_table,
    "status":"Not Done",
    "details":"This table shows the products of fissioning one ton of uranium. Most of it is uranium again, which could be reused via reprocessing. But with or without reprorcessing, the rest of the products would be generated. The transuranic elements (plutonium, neptunium, americium, curium) are generated by neutron bombardment of uranium during fission. I would like to break down short- and intermediate-lived fission products a bit more, but don't have good data. This is one where you will have to be clever in coming up with a good visualization.",
    "references":["hlw_products"],
    "source_file":"nuclear_waste.py"
})